### ISSUE TITLE
Results Screen Prev, Next, & Save Buttons --> Disable/Enable Read details

### ISSUE THREAD

**Issue by mxavier6** [dshimo/PaperTelephone#10]
Disable prev/next buttons when the user reaches the end of the list of images. Also disable save button when user saves an image

**Comment by AustinSiu** [comment]
I don't think we should disable the save button, as generally, applications don't prevent saving an image after someone saves it. Also, if they forget they've saved it and go back to it, they may question why they can't save -> more UI warnings and explanations.

**Comment by mxavier6** [comment]
Ok thats fine, just make sure to disable the save button when theres no image to save, or else the app will crash.
